### ISSUE TITLE
   System.IO.IOException: Not a directory

### ISSUE THREAD

**Issue by GRNY** [the-expanse/SideQuest#186]
it's not working with 0.4.0. error message is there. anyone have fix?
----
System.IO.IOException: Not a directory
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at SixLabors.ImageSharp.IO.LocalFileSystem.OpenRead(String path)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at LibSaberPatch.Utils.ImageFileToMipData(String imagePath, Int32 topDim) in /Users/travis/build/trishume/QuestSaberPatch/LibSaberPatch/Utils.cs:line 37
   at LibSaberPatch.AssetDataObjects.Texture2DAssetData.CoverFromImageFile(String filePath, String levelID, Boolean isPackCover) in /Users/travis/build/trishume/QuestSaberPatch/LibSaberPatch/AssetDataObjects/Texture2DAssetData.cs:line 48
   at LibSaberPatch.BehaviorDataObjects.LevelPackBehaviorData.CreateCustomPack(Transaction assets, String id, String name, String coverImagePath) in /Users/travis/build/trishume/QuestSaberPatch/LibSaberPatch/BehaviorDataObjects/LevelPackBehaviorData.cs:line 67
   at jsonApp.Program.SyncLevels(Apk apk, SerializedAssets mainAssets, Invocation inv, InvocationResult res) in /Users/travis/build/trishume/QuestSaberPatch/jsonApp2/Program.cs:line 176
   at jsonApp.Program.RunInvocation(Invocation inv) in /Users/travis/build/trishume/QuestSaberPatch/jsonApp2/Program.cs:line 92
-----

**Comment by GRNY** [comment]
plz move to discord for such issue.
