### ISSUE TITLE
Enhancement/BugFix: Preventive logic improvement for Pack Images

### ISSUE THREAD

**Issue by Mystic7AuDJa** [the-expanse/SideQuest#226]
For the Packs, when the custom songs page loads and prior to a sync can SideQuest query if the pictures for the packs are available and if they aren't set the folders back to the default image to help prevent:
System.IO.IOException: Not a directory
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at SixLabors.ImageSharp.IO.LocalFileSystem.OpenRead(String path)
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, String path)
   at LibSaberPatch.Utils.ImageFileToMipData(String imagePath, Int32 topDim) in /Users/travis/build/trishume/QuestSaberPatch/LibSaberPatch/Utils.cs:line 37
   at LibSaberPatch.AssetDataObjects.Texture2DAssetData.CoverFromImageFile(String filePath, String levelID, Boolean isPackCover) in /Users/travis/build/trishume/QuestSaberPatch/LibSaberPatch/AssetDataObjects/Texture2DAssetData.cs:line 48
   at LibSaberPatch.BehaviorDataObjects.LevelPackBehaviorData.CreateCustomPack(Transaction assets, String id, String name, String coverImagePath) in /Users/travis/build/trishume/QuestSaberPatch/LibSaberPatch/BehaviorDataObjects/LevelPackBehaviorData.cs:line 67
   at jsonApp.Program.SyncLevels(Apk apk, SerializedAssets mainAssets, Invocation inv, InvocationResult res) in /Users/travis/build/trishume/QuestSaberPatch/jsonApp2/Program.cs:line 176
   at jsonApp.Program.RunInvocation(Invocation inv) in /Users/travis/build/trishume/QuestSaberPatch/jsonApp2/Program.cs:line 92]

**Comment by Mystic7AuDJa** [comment]
Could even go a step further and in the error after the apk is built note that the location has been switched due to the image file not found for pack such and such.

**Comment by shaneharris** [comment]
It looks like were now migrating away from the old patcher, it will be there for a while for backwards compatibility but the next beat saber update will break it.

ill close this for now.
